-- Oracle schema for the Online Quiz Management System
-- Target: Oracle Database 23ai / 26ai Free, service FREEPDB1, user KRUTHIKA
-- Run as KRUTHIKA (SQL Developer: Run Script / F5, or SQL*Plus: @schema_oracle.sql).
-- IF NOT EXISTS needs 23ai or newer. The sample data at the bottom should be loaded only once.

CREATE TABLE IF NOT EXISTS quizzes (
    quiz_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR2(150 CHAR) NOT NULL,
    category         VARCHAR2(80 CHAR)  NOT NULL,
    duration_minutes NUMBER(4)          NOT NULL CHECK (duration_minutes >= 1),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS questions (
    question_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id        NUMBER NOT NULL,
    question_text  VARCHAR2(500 CHAR) NOT NULL,
    option_a       VARCHAR2(200 CHAR) NOT NULL,
    option_b       VARCHAR2(200 CHAR) NOT NULL,
    option_c       VARCHAR2(200 CHAR) NOT NULL,
    option_d       VARCHAR2(200 CHAR) NOT NULL,
    correct_answer CHAR(1) NOT NULL CHECK (correct_answer IN ('A', 'B', 'C', 'D')),
    CONSTRAINT fk_questions_quiz FOREIGN KEY (quiz_id)
        REFERENCES quizzes (quiz_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(100 CHAR) NOT NULL,
    email      VARCHAR2(150 CHAR) NOT NULL,
    CONSTRAINT uq_students_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS quiz_results (
    result_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id         NUMBER NOT NULL,
    student_id      NUMBER NOT NULL,
    score           NUMBER(4) NOT NULL,
    total_questions NUMBER(4) NOT NULL,
    percentage      NUMBER(5,2) NOT NULL,
    time_taken_sec  NUMBER(6) NOT NULL,
    attempted_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_results_quiz FOREIGN KEY (quiz_id)
        REFERENCES quizzes (quiz_id) ON DELETE CASCADE,
    CONSTRAINT fk_results_student FOREIGN KEY (student_id)
        REFERENCES students (student_id) ON DELETE CASCADE
);

-- Oracle does not index foreign keys automatically (MySQL did), so add them here
CREATE INDEX IF NOT EXISTS idx_questions_quiz ON questions (quiz_id);
CREATE INDEX IF NOT EXISTS idx_results_quiz_rank ON quiz_results (quiz_id, percentage, time_taken_sec);
CREATE INDEX IF NOT EXISTS idx_results_student ON quiz_results (student_id);

-- Sample data (run once). Questions look up their quiz by title instead of assuming ids 1 and 2.
INSERT INTO quizzes (title, category, duration_minutes) VALUES ('Java Basics', 'Programming', 5);
INSERT INTO quizzes (title, category, duration_minutes) VALUES ('General Knowledge - India', 'General', 5);

INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'Java Basics'),
        'Which keyword is used to inherit a class in Java?', 'implements', 'extends', 'inherits', 'super', 'B');
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'Java Basics'),
        'Which of these is not a primitive data type?', 'int', 'boolean', 'String', 'char', 'C');
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'Java Basics'),
        'What is the size of an int in Java?', '8 bits', '16 bits', '32 bits', '64 bits', 'C');
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'Java Basics'),
        'Which method is the entry point of a Java program?', 'start()', 'main()', 'run()', 'init()', 'B');
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'Java Basics'),
        'Which JDBC interface is used to run a parameterised SQL query?', 'Statement', 'PreparedStatement', 'ResultSet', 'DriverManager', 'B');

INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'General Knowledge - India'),
        'What is the capital of India?', 'Mumbai', 'Kolkata', 'New Delhi', 'Chennai', 'C');
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'General Knowledge - India'),
        'Who wrote the Indian national anthem?', 'Bankim Chandra Chatterjee', 'Rabindranath Tagore', 'Sarojini Naidu', 'Mahatma Gandhi', 'B');
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'General Knowledge - India'),
        'On which date is Republic Day celebrated in India?', '15 August', '26 January', '2 October', '14 November', 'B');
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'General Knowledge - India'),
        'Which is the largest Indian state by area?', 'Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Uttar Pradesh', 'C');
INSERT INTO questions (quiz_id, question_text, option_a, option_b, option_c, option_d, correct_answer)
VALUES ((SELECT quiz_id FROM quizzes WHERE title = 'General Knowledge - India'),
        'In which year did the Constitution of India come into effect?', '1947', '1948', '1950', '1952', 'C');

COMMIT;
